---
# The tasks defined in this role provide the requirements for Ansible
# provisioning on the managed nodes.
# http://docs.ansible.com/ansible/intro_installation.html#managed-node-requirements

- name: Check file stats of /var/log/schuerg.prerequisites.log
  stat:
    path: /var/log/schuerg.prerequisites.log
  register: st
- debug: var=st verbosity=4

- name: Check current time as Unix timestamp
  raw: date +%s
  register: timestamp
- debug: var=timestamp verbosity=4

- name: Perform the schuerg.prerequisites tasks only if needed
  include: setup.yml
  when: (st.stat.exists == false) or
        ((st.stat.mtime + 86400) < timestamp.stdout | int)
