---
# Perform the actual prerequisites tasks
#
# The tasks in this file will only be executed, if the schuerg.prerequisites
# role is not applied on the host in the last 24h.
# This is based on the logfile /var/log/schuerg.prerequisites.log

- name: Get the Linux distribution name using a raw command
  raw: cat /etc/os-release | grep -oP "^ID=\K.*"
  register: distribution

- name: Install Ansible requirements for Fedora
  raw: dnf install -y --allowerasing {{ item }}
  with_items: '{{ fedora_packages }}'
  when: distribution.stdout.find('fedora') != -1

- name: Install Ansible requirements for Centos
  raw: yum install -y {{ item }}
  with_items: '{{ centos_packages }}'
  when: distribution.stdout.find('centos') != -1

- name: Install Ansible requirements for Ubuntu
  raw: apt-get install -y {{ item }}
  with_items: '{{ ubuntu_packages }}'
  when: distribution.stdout.find('ubuntu') != -1

- name: Install Ansible requirements for Debian
  raw: apt-get install -y {{ item }}
  with_items: '{{ debian_packages }}'
  when: distribution.stdout.find('debian') != -1

- name: Install Ansible requirements for Alpine
  raw: apk --no-cache add {{ item }}
  with_items: '{{ alpine_packages }}'
  when: distribution.stdout.find('alpine') != -1

- name: Touch /var/log/schuerg.prerequisites.log
  file:
    path: /var/log/schuerg.prerequisites.log
    state: touch
