# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|

  config.vm.define "fedora" do |fedora|
    fedora.vm.box = "fedora/31-cloud-base"
    fedora.vm.box_version = "31.20191023.0"
    fedora.vm.network "private_network", ip: "172.16.100.10"

    fedora.vm.synced_folder ".", "/vagrant", type: "rsync",
    rsync__args: ["--verbose", "--archive", "--delete", "-z"]

    fedora.vm.provision :ansible do |ansible|
      ansible.playbook = "test.yml"
      ansible.inventory_path = "inventory"
    end
  end

  config.vm.define "centos" do |centos|
    centos.vm.box = "centos/8"
    centos.vm.box_version = "1905.1"
    centos.vm.network "private_network", ip: "172.16.100.20"

    centos.vm.synced_folder ".", "/vagrant", type: "rsync",
    rsync__args: ["--verbose", "--archive", "--delete", "-z"]

    centos.vm.provision :ansible do |ansible|
      ansible.playbook = "test.yml"
      ansible.inventory_path = "inventory"
    end
  end

  config.vm.define "ubuntu" do |ubuntu|
    ubuntu.vm.box = "ubuntu/bionic64"
    ubuntu.vm.network "private_network", ip: "172.16.100.30"

    ubuntu.vm.synced_folder ".", "/vagrant", type: "rsync",
    rsync__args: ["--verbose", "--archive", "--delete", "-z"]

    ubuntu.vm.provision :ansible do |ansible|
      ansible.playbook = "test.yml"
      ansible.inventory_path = "inventory"
    end
  end

  config.vm.define "debian" do |debian|
    debian.vm.box = "debian/buster64"
    debian.vm.network "private_network", ip: "172.16.100.40"

    debian.vm.synced_folder ".", "/vagrant", type: "rsync",
    rsync__args: ["--verbose", "--archive", "--delete", "-z"]

    debian.vm.provision :ansible do |ansible|
      ansible.playbook = "test.yml"
      ansible.inventory_path = "inventory"
    end
  end

  config.vm.define "alpine" do |alpine|
    alpine.vm.box = "generic/alpine310"
    alpine.vm.network "private_network", ip: "172.16.100.50"

    alpine.vm.synced_folder ".", "/vagrant", type: "rsync",
    rsync__args: ["--verbose", "--archive", "--delete", "-z"]

    alpine.vm.provision :ansible do |ansible|
      ansible.playbook = "test.yml"
      ansible.inventory_path = "inventory"
    end
  end

end
